# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci = [1, 2, 3]

# complete fibonacci sequence up to 4 million (last term must be less than 4000000)
while fibonacci[len(fibonacci)-1] < 4000000:
    next_num = fibonacci[len(fibonacci)-1] + fibonacci[len(fibonacci)-2]
    fibonacci.append(next_num)

result = 0
for i in fibonacci:
    if (i % 2 == 0):
        result += i

print(result)

# Answer: 4613732
