# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
# However, their difference, 70 − 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal
# and D = |Pk − Pj| is minimised; what is the value of D?

from time import time
start = time()

from module import is_pentagonal

pentagonal_numbers = [1, 5]
not_finished = True
i = 3
good_numbers = []

while not_finished:
    next_num = ((3 * i * i) - i) / 2
    for n in pentagonal_numbers:
        d = abs(n - next_num)
        if is_pentagonal(next_num + n) and is_pentagonal(d):
            print(int(d))
            not_finished = False
    pentagonal_numbers.append(int(next_num))
    i += 1

print(time() - start)

# Answer: 5482660
