# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle 	  	    Tn = n(n+1)/2 	  	1, 3, 6, 10, 15, ...
# Pentagonal 	  	Pn = n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
# Hexagonal 	  	Hn = n(2n−1) 	  	    1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.

from time import time
start = time()

from module import is_pentagonal, is_hexagonal

for i in range(286, 100000):
    tri_num = ((i * i) + i) / 2
    if is_pentagonal(tri_num) and is_hexagonal(tri_num):
        print(int(tri_num))
        break

print(time() - start)

# Answer: 1533776805
